# Generated by Django 2.2.6 on 2019-10-04 02:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='text'),
            preserve_default=False,
        ),
    ]
